# wdi - WORD DEVELOPMENT INDICATORS
# BASE DE DADOS DO BANCO MUNDIAL

install.packages("WDI")
library(WDI)
# SEMPRE PROCUREM AS VIGNETTES
# PAGINAS COM ORIENTAÇÕES DOS PACOTES

# BAIXAR OS DADOS DO PIB (PRODUTO INTERNO BRUTO)
# TUDO O QUE É PRODUZIDO EM UM PAÍS/ESTADO/MUN.
# EM UM DETERMINADO PERIODO

# GDP (current US$)(NY.GDP.MKTP.CD)
# GROSS DOMESTIC PRODUCT (GDP) EM DÓLARES NORTE-AMERICANOS
# CÓDIGO NY.GDP.MKTP.CD

COD_GDP <- WDIsearch('gdp')
# É IMPORTANTE PROCURAR PELO PRÓPRIO
# SITE DO BANCO MUNDIAL, É MAIS
# EFICIENTE

# COM O CÓDIGO, VAMOS BAIXAR OS DADOS

options(scipen = 999) # AJUSTAR NÚMEROS (NOT. CIENT.)
basepib <- WDI(country = 'all',indicator = 'NY.GDP.MKTP.CD')

basepib2023 <- WDI(country = 'all',indicator = 'NY.GDP.MKTP.CD',start = 2023, end = 2023)
